name: Workflow-Übung
on: 
    push:
        branches: 
            - master
    pull_request: 
            branches: 
             - master
   

jobs:
    Explore-Github-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: cloning repository
              run: git "https://github.com/hasib9669/springboot-backend.git"
            - name: "Build"
              run: mvn clean install
              
            

            


