name: Workflow-Übung
on: 
    push:
        branches: 
            - master
    pull_request: 
            branches: 
             - master
   

jobs:
      Github_Actions:
        runs-on: ubuntu-latest
        steps:
            - name: cloning repository
              run: git clone https://github.com/hasib9669/springboot-backend.git
            - name: "Build"
              run: |
                cd springboot-backend
                mvn clean 
                mvn package

            - name: "Test"
              run: |
                cd springboot-backend
                mvn test
            - name: "Deploy"
              run: echo "Build deployed"
              
            

            


